name: dictionary
description: "Arabic Dictionary"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

    # IU
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.3
  flip_card: ^0.7.0
  smooth_page_indicator: ^1.2.1
  flutter_card_swiper: ^7.1.0

  # Databases
  sqflite: ^2.4.2
  hive_flutter: ^1.1.0

  # System
  path: ^1.9.1
  intl: ^0.20.2
  timezone: ^0.10.1
  wakelock_plus: ^1.4.0
  url_launcher: ^6.3.2

  # Copy/Share
  share_plus: ^12.0.0
  clipboard: ^2.0.2

  # State management
  provider: ^6.1.5+1

  # Notifications
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: 'Uthmanic'
      fonts:
        - asset: assets/fonts/uthmanic.ttf
    - family: 'SF Pro'
      fonts:
        - asset: assets/fonts/sf_pro.ttf
    - family: 'SF Pro Regular'
      fonts:
        - asset: assets/fonts/sf_pro_regular.ttf
    - family: 'Heuristica'
      fonts:
        - asset: assets/fonts/heuristica.ttf
